package com.example.project.Donations;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import java.sql.Timestamp;
import com.example.project.Blood_Requests.Blood_Requests_Model;
import com.example.project.Donor_Profiles.Donor_Profiles_Model;

/**
 * Entity class representing a blood donation record in the system.
 * <p>
 * Each {@code Donations_Model} instance corresponds to a single donation event,
 * linking a {@link Donor_Profiles_Model} (the donor) to a
 * {@link Blood_Requests_Model} (the fulfilled blood request).
 *
 * <p><b>Table:</b> {@code donations}
 *
 * <p><b>Relationships:</b>
 * <ul>
 *   <li>Many-to-One with {@link Donor_Profiles_Model} — identifies the donor.</li>
 *   <li>Many-to-One with {@link Blood_Requests_Model} — identifies the fulfilled request.</li>
 * </ul>
 *
 * <p><b>Managed by:</b>
 * <ul>
 *   <li>{@link Donations_Controller} — for RESTful operations.</li>
 *   <li>{@link Donations_Repository} — for database persistence.</li>
 * </ul>
 *
 * @version 1.0
 */
@Entity
@Table(name = "donations")
public class Donations_Model {

    // =========================
    // Primary Key
    // =========================

    /**
     * Unique identifier for each donation record.
     * Auto-generated by the database using identity strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "donation_id")
    private Long donationId;

    // =========================
    // Donation Details
    // =========================

    /**
     * Number of blood units donated (must be non-negative).
     */
    @Min(0)
    @Column(name = "units_donated", nullable = false)
    private int unitsDonated;

    /**
     * Outcome of the donation process (e.g., "Successful", "Deferred", "Cancelled").
     * This field cannot be blank.
     */
    @NotBlank
    @Column(name = "outcome", nullable = false)
    private String outcome;

    /**
     * Timestamp representing when the donation took place.
     * Must be a past or present date/time.
     */
    @PastOrPresent
    @Column(name = "donation_time")
    private Timestamp donationTime;

    /**
     * Indicates whether the donation was confirmed by the requester (hospital or patient).
     */
    @NotNull
    @Column(name = "confirmed_by_requester")
    private Boolean confirmedByRequester;

    /**
     * Timestamp representing when the donation record was created in the database.
     * Automatically set when the entity is first persisted.
     */
    @PastOrPresent
    @Column(name = "created_at")
    private Timestamp createdAt;

    // =========================
    // Relationships
    // =========================

    /**
     * Reference to the donor who made the donation.
     * <p>
     * Uses EAGER fetching since donor information is typically needed alongside donation data.
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "donor_id", nullable = false)
    private Donor_Profiles_Model donorProfile;

    /**
     * Reference to the fulfilled blood request.
     * <p>
     * Links each donation to the corresponding {@link Blood_Requests_Model} record.
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "request_id", nullable = false)
    private Blood_Requests_Model fulfilledRequest;

    // =========================
    // Constructors & Lifecycle
    // =========================

    /** Default constructor required by JPA. */
    public Donations_Model() {}

    /**
     * Lifecycle callback that initializes timestamps before persisting a new record.
     * <p>
     * If {@code createdAt} or {@code donationTime} are not set, they default to the current system time.
     */
    @PrePersist
    protected void onCreate() {
        if (createdAt == null) createdAt = new Timestamp(System.currentTimeMillis());
        if (donationTime == null) donationTime = new Timestamp(System.currentTimeMillis());
    }

    // =========================
    // Getters and Setters
    // =========================

    /** @return the unique donation ID */
    public Long getDonationId() { return donationId; }

    /** @param donationId sets the unique donation ID */
    public void setDonationId(Long donationId) { this.donationId = donationId; }

    /** @return number of blood units donated */
    public int getUnitsDonated() { return unitsDonated; }

    /** @param unitsDonated sets the number of blood units donated */
    public void setUnitsDonated(int unitsDonated) { this.unitsDonated = unitsDonated; }

    /** @return the donation outcome (e.g., "Successful") */
    public String getOutcome() { return outcome; }

    /** @param outcome sets the donation outcome */
    public void setOutcome(String outcome) { this.outcome = outcome; }

    /** @return timestamp of when the donation occurred */
    public Timestamp getDonationTime() { return donationTime; }

    /** @param donationTime sets the donation timestamp */
    public void setDonationTime(Timestamp donationTime) { this.donationTime = donationTime; }

    /** @return whether the donation was confirmed by the requester */
    public Boolean getConfirmedByRequester() { return confirmedByRequester; }

    /** @param confirmedByRequester sets whether the donation was confirmed by the requester */
    public void setConfirmedByRequester(Boolean confirmedByRequester) { this.confirmedByRequester = confirmedByRequester; }

    /** @return timestamp of when this record was created */
    public Timestamp getCreatedAt() { return createdAt; }

    /** @param createdAt sets the creation timestamp (optional override) */
    public void setCreatedAt(Timestamp createdAt) { this.createdAt = createdAt; }

    /** @return the donor profile associated with this donation */
    public Donor_Profiles_Model getDonorProfile() { return donorProfile; }

    /** @param donorProfile sets the donor profile associated with this donation */
    public void setDonorProfile(Donor_Profiles_Model donorProfile) { this.donorProfile = donorProfile; }

    /** @return the fulfilled blood request associated with this donation */
    public Blood_Requests_Model getFulfilledRequest() { return fulfilledRequest; }

    /** @param fulfilledRequest sets the fulfilled blood request associated with this donation */
    public void setFulfilledRequest(Blood_Requests_Model fulfilledRequest) { this.fulfilledRequest = fulfilledRequest; }
}
