package com.example.project.Donor_Pledges;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import java.sql.Timestamp;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.example.project.Blood_Requests.Blood_Requests_Model;
import com.example.project.Donor_Profiles.Donor_Profiles_Model;

/**
 * Entity class representing a donor pledge in the system.
 * <p>
 * A donor pledge is a commitment made by a donor to fulfill a specific
 * {@link Blood_Requests_Model} in the near future. It includes details about
 * the pledged blood units, status, and messages exchanged between the donor
 * and the requester.
 *
 * <p><b>Table:</b> {@code donor_pledges}
 *
 * <p><b>Relationships:</b>
 * <ul>
 *   <li>Many-to-One with {@link Donor_Profiles_Model} — identifies the donor making the pledge.</li>
 *   <li>Many-to-One with {@link Blood_Requests_Model} — identifies the blood request being pledged to.</li>
 * </ul>
 *
 * <p><b>Lifecycle Events:</b>
 * <ul>
 *   <li>{@link #onCreate()} — Initializes timestamps at creation.</li>
 *   <li>{@link #onUpdate()} — Updates {@code updatedAt} whenever a record is modified.</li>
 * </ul>
 *
 * <p>Managed through the {@link Donor_Pledges_Controller} and persisted via
 * {@link Donor_Pledges_Repository}.
 *
 * @version 1.0
 */
@Entity
@Table(name = "donor_pledges")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Donor_Pledges_Model {

    // =========================
    // Primary Key
    // =========================

    /**
     * Unique identifier for each donor pledge.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "pledge_id")
    private Long pledgeId;

    // =========================
    // Core Attributes
    // =========================

    /**
     * Current status of the pledge (e.g., "Active", "Pending", "Cancelled", "Completed").
     */
    @NotBlank
    @Column(name = "pledge_status", nullable = false)
    private String pledgeStatus;

    /**
     * Number of blood units the donor has pledged to provide.
     * Must be non-negative.
     */
    @Min(0)
    @Column(name = "pledged_units", nullable = false)
    private int pledgedUnits;

    /**
     * Optional message accompanying the pledge — typically used by the donor
     * to provide context, motivation, or scheduling notes.
     */
    @NotBlank
    @Column(name = "message", nullable = false)
    private String message;

    /**
     * Timestamp recording the most recent update to this pledge record.
     * Automatically updated before each persistence operation.
     */
    @PastOrPresent
    @Column(name = "updated_at")
    private Timestamp updatedAt;

    /**
     * Timestamp recording when this pledge was initially created.
     * Automatically populated on first persistence.
     */
    @PastOrPresent
    @Column(name = "created_at")
    private Timestamp createdAt;

    // =========================
    // Relationships
    // =========================

    /**
     * The donor profile associated with this pledge.
     * <p>
     * Uses EAGER fetching since donor data is commonly accessed with pledge details.
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "donor_id", nullable = false)
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler", "user"})
    private Donor_Profiles_Model donorProfile;

    /**
     * The blood request that this pledge is intended to fulfill.
     * <p>
     * Uses EAGER fetching to ensure request data is readily available when retrieving pledges.
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "request_id", nullable = false)
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler", "user"})
    private Blood_Requests_Model matchedRequest;

    // =========================
    // Constructors & Lifecycle
    // =========================

    /** Default constructor required by JPA. */
    public Donor_Pledges_Model() {}

    /**
     * Lifecycle callback triggered before a new record is persisted.
     * <p>
     * Automatically initializes {@code createdAt} and {@code updatedAt}
     * timestamps if they are not already set.
     */
    @PrePersist
    protected void onCreate() {
        if (createdAt == null) createdAt = new Timestamp(System.currentTimeMillis());
        if (updatedAt == null) updatedAt = new Timestamp(System.currentTimeMillis());
    }

    /**
     * Lifecycle callback triggered before any update to this entity.
     * <p>
     * Automatically refreshes the {@code updatedAt} timestamp.
     */
    @PreUpdate
    protected void onUpdate() {
        updatedAt = new Timestamp(System.currentTimeMillis());
    }

    // =========================
    // Getters and Setters
    // =========================

    /** @return the unique pledge ID */
    public Long getPledgeId() { return pledgeId; }

    /** @param pledgeId sets the unique pledge ID */
    public void setPledgeId(Long pledgeId) { this.pledgeId = pledgeId; }

    /** @return the current pledge status */
    public String getPledgeStatus() { return pledgeStatus; }

    /** @param pledgeStatus sets the current pledge status */
    public void setPledgeStatus(String pledgeStatus) { this.pledgeStatus = pledgeStatus; }

    /** @return number of blood units pledged */
    public int getPledgedUnits() { return pledgedUnits; }

    /** @param pledgedUnits sets the number of blood units pledged */
    public void setPledgedUnits(int pledgedUnits) { this.pledgedUnits = pledgedUnits; }

    /** @return the donor’s message */
    public String getMessage() { return message; }

    /** @param message sets the donor’s message */
    public void setMessage(String message) { this.message = message; }

    /** @return the last update timestamp */
    public Timestamp getUpdatedAt() { return updatedAt; }

    /** @param updatedAt sets the last update timestamp */
    public void setUpdatedAt(Timestamp updatedAt) { this.updatedAt = updatedAt; }

    /** @return the creation timestamp */
    public Timestamp getCreatedAt() { return createdAt; }

    /** @param createdAt sets the creation timestamp */
    public void setCreatedAt(Timestamp createdAt) { this.createdAt = createdAt; }

    /** @return the donor profile linked to this pledge */
    public Donor_Profiles_Model getDonorProfile() { return donorProfile; }

    /** @param donorProfile sets the donor profile linked to this pledge */
    public void setDonorProfile(Donor_Profiles_Model donorProfile) { this.donorProfile = donorProfile; }

    /** @return the blood request this pledge is fulfilling */
    public Blood_Requests_Model getMatchedRequest() { return matchedRequest; }

    /** @param matchedRequest sets the blood request this pledge is fulfilling */
    public void setMatchedRequest(Blood_Requests_Model matchedRequest) { this.matchedRequest = matchedRequest; }
}
