package com.example.project.Users;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import java.sql.Timestamp;

/**
 * Entity class representing a system user.
 * <p>
 * Each {@code User_Model} instance corresponds to a record in the {@code user_model} table.
 * A user record contains personal details, authentication credentials, and metadata used
 * across related modules such as donor profiles, pledges, and donations.
 *
 * <p><b>Table:</b> {@code user_model}
 *
 * <p><b>Usage:</b>
 * <ul>
 *   <li>Linked to {@link com.example.project.Donor_Profiles.Donor_Profiles_Model} as a parent entity.</li>
 *   <li>Serves as the base entity for authentication in {@link com.example.project.Auth.AuthService}.</li>
 * </ul>
 *
 * @version 1.0
 */
@Entity
@Table(name = "user_model")
public class User_Model {

    // =========================
    // Primary Key
    // =========================

    /**
     * Unique identifier for each user.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "user_id")
    private Long userId;

    // =========================
    // User Information
    // =========================

    /**
     * The user's full name (first and last).
     */
    @NotBlank
    @Column(name = "full_name")
    private String fullName;

    /**
     * The user's unique email address.
     * <p>
     * Used as the primary credential for login and must conform to standard email format.
     */
    @Email
    @NotBlank
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * The user's phone number (used for contact or emergency verification).
     */
    @NotBlank
    private String phone;

    /**
     * Hashed password for user authentication.
     * <p>
     * Stored securely after encryption using BCrypt (see {@link com.example.project.Auth.AuthService}).
     */
    @NotBlank
    @Column(name = "password_hash", nullable = false)
    private String passwordHash;

    /**
     * The user's system role (e.g., "USER", "Donor", "Admin").
     * Defaults to {@code "USER"} if not specified.
     */
    @NotBlank
    private String role = "USER";

    /**
     * The user's residential or home address.
     */
    @NotBlank
    @Column(name = "home_address")
    private String homeAddress;

    /**
     * The user's blood type (e.g., "A", "B", "AB", "O").
     */
    @NotBlank
    @Column(name = "blood_type")
    private String bloodType;

    /**
     * The user's Rhesus factor (e.g., "+" or "-").
     */
    @NotBlank
    private String rhesus;

    /**
     * Timestamp representing when the user record was created.
     * <p>
     * Automatically initialized at the time of persistence.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Timestamp createdAt = new Timestamp(System.currentTimeMillis());

    // =========================
    // Constructors
    // =========================

    /** Default constructor required by JPA. */
    public User_Model() {}

    /**
     * Constructs a fully initialized {@code User_Model} instance.
     *
     * @param fullName     the user's full name
     * @param email        the user's email address
     * @param phone        the user's phone number
     * @param passwordHash the hashed password
     * @param role         the user's system role
     * @param homeAddress  the user's home address
     * @param bloodType    the user's blood type
     * @param rhesus       the user's Rhesus factor
     */
    public User_Model(String fullName, String email, String phone, String passwordHash,
                      String role, String homeAddress, String bloodType, String rhesus) {
        this.fullName = fullName;
        this.email = email;
        this.phone = phone;
        this.passwordHash = passwordHash;
        this.role = role;
        this.homeAddress = homeAddress;
        this.bloodType = bloodType;
        this.rhesus = rhesus;
        this.createdAt = new Timestamp(System.currentTimeMillis());
    }

    // =========================
    // Lifecycle Events
    // =========================

    /**
     * Lifecycle callback that sets the {@code createdAt} timestamp before persisting the entity.
     */
    @PrePersist
    protected void onCreate() {
        if (createdAt == null) {
            createdAt = new Timestamp(System.currentTimeMillis());
        }
    }

    // =========================
    // Getters and Setters
    // =========================

    /** @return the unique user ID */
    public Long getUserId() { return userId; }

    /** @param userId sets the unique user ID */
    public void setUserId(Long userId) { this.userId = userId; }

    /** @return the user's full name */
    public String getFullName() { return fullName; }

    /** @param fullName sets the user's full name */
    public void setFullName(String fullName) { this.fullName = fullName; }

    /** @return the user's email address */
    public String getEmail() { return email; }

    /** @param email sets the user's email address */
    public void setEmail(String email) { this.email = email; }

    /** @return the user's phone number */
    public String getPhone() { return phone; }

    /** @param phone sets the user's phone number */
    public void setPhone(String phone) { this.phone = phone; }

    /** @return the hashed password */
    public String getPasswordHash() { return passwordHash; }

    /** @param passwordHash sets the hashed password */
    public void setPasswordHash(String passwordHash) { this.passwordHash = passwordHash; }

    /** @return the user's role */
    public String getRole() { return role; }

    /** @param role sets the user's role */
    public void setRole(String role) { this.role = role; }

    /** @return the user's home address */
    public String getHomeAddress() { return homeAddress; }

    /** @param homeAddress sets the user's home address */
    public void setHomeAddress(String homeAddress) { this.homeAddress = homeAddress; }

    /** @return the user's blood type */
    public String getBloodType() { return bloodType; }

    /** @param bloodType sets the user's blood type */
    public void setBloodType(String bloodType) { this.bloodType = bloodType; }

    /** @return the user's Rhesus factor */
    public String getRhesus() { return rhesus; }

    /** @param rhesus sets the user's Rhesus factor */
    public void setRhesus(String rhesus) { this.rhesus = rhesus; }

    /** @return the timestamp of when this user record was created */
    public Timestamp getCreatedAt() { return createdAt; }

    /** @param createdAt sets the creation timestamp */
    public void setCreatedAt(Timestamp createdAt) { this.createdAt = createdAt; }
}
